<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_profile</name>
   <tag></tag>
   <elementGuidId>850c8181-14f3-4e48-80f9-fc0f22056c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loading-label > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='loading-label']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4af18e80-4ed7-40bb-8c58-26b982c9c139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/profile</value>
      <webElementGuid>260c1a47-ad75-4587-ab1d-cb2bbf2390db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>profile</value>
      <webElementGuid>a7d8aef4-df9d-4a6d-b5f4-8cdfb52edc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loading-label&quot;)/a[1]</value>
      <webElementGuid>71a0f9eb-86ab-4ab5-9d30-3e5b3f0615cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='loading-label']/a</value>
      <webElementGuid>0e1a252c-0632-4990-9d8d-a20d3a9566c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'profile')]</value>
      <webElementGuid>0ef25044-f8e7-44fc-b229-63ce1399ecd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/profile')]</value>
      <webElementGuid>788d12d1-a4bd-4441-b590-7e0fb82af1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>88f3da11-aad6-41e4-8a24-662e1dbe0cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/profile' and (text() = 'profile' or . = 'profile')]</value>
      <webElementGuid>c068a1d7-f99f-451d-9843-18921aa38fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
