<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aclose-fixedban</name>
   <tag></tag>
   <elementGuidId>ca58c70d-8d9b-4426-b3b1-92bdc48e1c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-fixedban</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='close-fixedban']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54cc2dfa-aea5-4f6f-8f95-546530b7f0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-fixedban</value>
      <webElementGuid>4f7e4e4a-54ca-40b1-8ce7-43916bc1c1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById(&quot;fixedban&amp;apos&quot;).style.display=&quot;none&amp;apos&quot;</value>
      <webElementGuid>b885a47b-fb82-479b-a292-551805ef3ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-fixedban&quot;)</value>
      <webElementGuid>473eb0d8-65e5-4071-bf6f-0db8789f843b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='close-fixedban']</value>
      <webElementGuid>b09651e0-aa59-4a67-96e7-f0a60d128e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fixedban']/div/div/a</value>
      <webElementGuid>f0b37b96-7850-4553-aa40-43ee87e1913b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>078996a7-5a66-480f-a130-cb95bf02b1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'close-fixedban']</value>
      <webElementGuid>febc4548-be45-474f-a5a0-0c293e0e335e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
