<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go To Book Store</name>
   <tag></tag>
   <elementGuidId>a99c1cc7-9dc7-48e1-a73d-0bb58bf1977f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gotoStore</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gotoStore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24bee906-6699-4784-a331-3f833aecd233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gotoStore</value>
      <webElementGuid>38608397-13a1-4771-94fd-c366e290e15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6335bbd6-5f2a-4c29-8a75-a1524e07cf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>53b15bb4-c977-46d4-bde0-02c32fea4ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go To Book Store</value>
      <webElementGuid>60a68c46-86bb-4441-a73a-5870ddd1966a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gotoStore&quot;)</value>
      <webElementGuid>be73e686-c0b8-4050-8776-73da14729ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gotoStore']</value>
      <webElementGuid>00ff972c-780d-4baa-98a6-09dc01747a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[3]/div/button</value>
      <webElementGuid>39a16210-e70e-4681-a1d3-5c4151f0ad57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>6780d56d-3679-4f93-9a48-36284cef942f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gotoStore' and @type = 'button' and (text() = 'Go To Book Store' or . = 'Go To Book Store')]</value>
      <webElementGuid>ef76e1cb-b81d-49ad-b963-5970441c89b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
