<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Image</name>
   <tag></tag>
   <elementGuidId>e5d90f6d-a9e2-48da-9678-6a0b8fb4d104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rt-resizable-header-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb181a2e-e7eb-4f97-8de9-eca4dc891128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rt-resizable-header-content</value>
      <webElementGuid>d38ae2fe-ec27-4eca-b4c8-56e58e6aa150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Image</value>
      <webElementGuid>f191e622-6290-46f5-a3cc-0d280ef5c2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;container playgound-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mt-4 col-md-6&quot;]/div[@class=&quot;profile-wrapper&quot;]/div[@class=&quot;ReactTable -striped -highlight&quot;]/div[@class=&quot;rt-table&quot;]/div[@class=&quot;rt-thead -header&quot;]/div[@class=&quot;rt-tr&quot;]/div[@class=&quot;rt-th rt-resizable-header -cursor-pointer&quot;]/div[@class=&quot;rt-resizable-header-content&quot;]</value>
      <webElementGuid>25ca7804-4f1e-4e1e-ae37-201d7b524355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>f4440ea2-b15d-4f7f-aa14-6871c9f560df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>51574c70-1e61-4412-9f4b-d5cef75b6470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Image' or . = 'Image')]</value>
      <webElementGuid>f36a249a-bb40-4084-9142-d9f54d125232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
