<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divadplus-anchor</name>
   <tag></tag>
   <elementGuidId>2b849163-aa0b-4e80-aba5-a0a3192f0bcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adplus-anchor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adplus-anchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e1ae169-2bcc-408d-ba5c-9695e3d4d545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adplus-anchor</value>
      <webElementGuid>aebc1c23-771a-4f2e-8b20-15028da6d18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-query-id</name>
      <type>Main</type>
      <value>CPai7-LdhoQDFfhRnQkd1SUEnw</value>
      <webElementGuid>ce6449bd-c97a-4029-a501-92f8c5437144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adplus-anchor&quot;)</value>
      <webElementGuid>b5bab289-f009-4a1f-a449-9bceb6017909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='adplus-anchor']</value>
      <webElementGuid>2f10332c-b97e-4727-966f-df1aafb55d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fixedban']/div/div[2]</value>
      <webElementGuid>67974255-ead8-469c-af12-f8775bb549ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>52fd885c-5e8f-43ee-8e41-d42682c9b021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'adplus-anchor']</value>
      <webElementGuid>062fab5e-5c4d-4d91-8311-bab3cc668663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
