<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Welcome,Login in Book StoreUserName  P_1bd0cd</name>
   <tag></tag>
   <elementGuidId>69dad087-1566-4dc0-8c75-7a768131d6e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>15a3f150-93f1-4416-a531-58917aac43ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userForm</value>
      <webElementGuid>b4ca9558-d6fc-4384-a8bb-d83e5c0bbd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome,Login in Book StoreUserName : Password : LoginNew User</value>
      <webElementGuid>145df740-1399-47ac-868d-f2103f19f511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userForm&quot;)</value>
      <webElementGuid>4856c87e-cc9e-4933-abb5-57928a1cd702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='userForm']</value>
      <webElementGuid>74741871-cc6c-4e99-b1c9-5c8269298b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/form</value>
      <webElementGuid>87d36f1c-a4fc-4130-b863-2c490bdfeabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>aad32caf-776d-4842-b7b3-a49b2d124edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'userForm' and (text() = 'Welcome,Login in Book StoreUserName : Password : LoginNew User' or . = 'Welcome,Login in Book StoreUserName : Password : LoginNew User')]</value>
      <webElementGuid>b12ccac6-430b-4293-abf7-cec5b6682349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
