<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>08ea8399-57e0-4bee-ba1b-e09e4d48e93f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;adplus-dvertising&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='close-fixedban']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>16172a2a-9b4a-4221-9c4d-9723a35e5bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ad.plus/adplus-advertising.svg</value>
      <webElementGuid>6f25f922-a9d0-4809-a6ab-73164c76e460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>adplus-dvertising</value>
      <webElementGuid>e12c528b-f5f6-4df2-a00f-9b0ed99b5a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ad.Plus Advertising</value>
      <webElementGuid>63e213ad-850d-4391-bf8d-bb3c566cd5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-fixedban&quot;)/img[1]</value>
      <webElementGuid>09e6fd10-268c-405a-a8dc-6940ae326df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='close-fixedban']/img</value>
      <webElementGuid>2e071e5d-c3d0-4e62-9bea-48c48d69ce01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='adplus-dvertising']</value>
      <webElementGuid>a2b760f8-e8b6-4e9e-8a18-951f0604e878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bd3222f8-81ed-4491-a9c9-c2a2cd8c80c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ad.plus/adplus-advertising.svg' and @alt = 'adplus-dvertising' and @title = 'Ad.Plus Advertising']</value>
      <webElementGuid>70331d55-77ea-4320-ba5d-ef33a6687c73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
