<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>1382d00a-e809-41bb-9ecd-ecbf339eabfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0b6318fc-1ed7-45e2-8e9d-dc24c0c5653b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c409e3ab-03d3-41ca-b78c-65d09bef662e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA555pQnciWdrmZDrBh5TjmLyaMo2dZkcaq7TJUJfEHewrqOavC8qpEj-jceBoh9wPfnXnk9N1Ru1YHidLiCX6-0qt2fM0xfOGHXZS-gPkYyWbUI2YAkHhtM78hc2V7-dA5kgus0dGzMOm0UorLW46rIYRfifVSWZvYm7s6y_SHFKpiOJACo26wYvDCtG61H4MC1H1iB&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>7d6e3990-78e0-4fa6-bcf2-87fcf7e068e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>4037afd7-5d3e-415e-928e-e4b06703372a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DEMOQA/iframe_c-88nofmdjmtwl</value>
      <webElementGuid>55b985c0-9bad-4180-8a4a-ac40dbb2a69a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>edb477a1-e1f8-4d03-834e-547925bdd1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA555pQnciWdrmZDrBh5TjmLyaMo2dZkcaq7TJUJfEHewrqOavC8qpEj-jceBoh9wPfnXnk9N1Ru1YHidLiCX6-0qt2fM0xfOGHXZS-gPkYyWbUI2YAkHhtM78hc2V7-dA5kgus0dGzMOm0UorLW46rIYRfifVSWZvYm7s6y_SHFKpiOJACo26wYvDCtG61H4MC1H1iB&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')])[4]</value>
      <webElementGuid>be709736-bc28-441c-9b70-1c9863e6b4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>4e140ff8-be08-4b3e-bb91-3f5ff826f452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA555pQnciWdrmZDrBh5TjmLyaMo2dZkcaq7TJUJfEHewrqOavC8qpEj-jceBoh9wPfnXnk9N1Ru1YHidLiCX6-0qt2fM0xfOGHXZS-gPkYyWbUI2YAkHhtM78hc2V7-dA5kgus0dGzMOm0UorLW46rIYRfifVSWZvYm7s6y_SHFKpiOJACo26wYvDCtG61H4MC1H1iB&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>36b56651-3719-45a1-8468-b2da89651bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6DjnbN2fX_myzkdBYjPxehOSHky4jQcrcd3Yr6kyWMZhCZGuveKB70kih3fmr8DnWCkfOOufNId7f7nHzI3g89fHSB6fyjSW9rj4S9oGZvZoxYv3vI0x_iKUXxqZnZ7h3LSOpx8hqN1te2Yh_6Zh51Iq8FJp2NsYbq-FTXY1fdZA4ZdSUSc0BphWV6Ze9vaVKLO90m&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')])[4]</value>
      <webElementGuid>43e3569f-250a-4319-aa9c-dcee0e1f7a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6DjnbN2fX_myzkdBYjPxehOSHky4jQcrcd3Yr6kyWMZhCZGuveKB70kih3fmr8DnWCkfOOufNId7f7nHzI3g89fHSB6fyjSW9rj4S9oGZvZoxYv3vI0x_iKUXxqZnZ7h3LSOpx8hqN1te2Yh_6Zh51Iq8FJp2NsYbq-FTXY1fdZA4ZdSUSc0BphWV6Ze9vaVKLO90m&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>ccb448a8-36ac-4ec4-a9b3-1e2b85cd1d94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
