<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>a61a9813-b149-417f-89ee-41d709f7e177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5872f072-1c5a-4f15-85f9-f49a55c150fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>6ece599f-e623-406a-a859-093e44fb337c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4EL2Lp1kAPkm2sDmd0ZnjJ1ysu27ERcpBMVxHxrJTUxnXWhzhmTv22IV68IN3Pp6ccCRwzlNrNz3jQb7tbPPYoGb7o4x6aVEyWG-G-_lA1QMVORaI4Y1DckkCVzUApJFkZJsjRRWjBFMI3OLiW0w4t0FfcIcZ1AsSQ556uv8gM9EBe7RBmtECVHsm2CbZcvQ9W0a5N&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>f07cbf71-8b9d-4d02-ac85-8c4b03e4e881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>716c0479-3798-4b12-8aec-62e00cce0c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DEMOQA/iframe_c-88nofmdjmtwl</value>
      <webElementGuid>e699eec1-379e-4b82-977d-06dc0986bc67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>ae4da074-c3bc-4ee4-bf69-34d8267de7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4EL2Lp1kAPkm2sDmd0ZnjJ1ysu27ERcpBMVxHxrJTUxnXWhzhmTv22IV68IN3Pp6ccCRwzlNrNz3jQb7tbPPYoGb7o4x6aVEyWG-G-_lA1QMVORaI4Y1DckkCVzUApJFkZJsjRRWjBFMI3OLiW0w4t0FfcIcZ1AsSQ556uv8gM9EBe7RBmtECVHsm2CbZcvQ9W0a5N&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')])[10]</value>
      <webElementGuid>dfcc9cec-2852-454f-bc17-fd43458cc705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>ab56e2ba-77c4-48b0-917a-c798b3e16690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4EL2Lp1kAPkm2sDmd0ZnjJ1ysu27ERcpBMVxHxrJTUxnXWhzhmTv22IV68IN3Pp6ccCRwzlNrNz3jQb7tbPPYoGb7o4x6aVEyWG-G-_lA1QMVORaI4Y1DckkCVzUApJFkZJsjRRWjBFMI3OLiW0w4t0FfcIcZ1AsSQ556uv8gM9EBe7RBmtECVHsm2CbZcvQ9W0a5N&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>d65e43e1-5b53-4bc3-8547-59163b2b7de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
