<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_With Learning JavaScript Design Patte_7022d9</name>
   <tag></tag>
   <elementGuidId>1b9c7a34-10ab-41f4-93ed-aea7e25fcec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description-wrapper > div.col-md-9.col-sm-12 > #userName-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[@id='userName-value'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f1322874-a6cc-40ff-b148-ff7f174ee81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>0df2eee2-8a47-4d9a-afab-5b60ccd032b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>becf7fa1-40ba-4eca-a775-7690da65ebb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName-value</value>
      <webElementGuid>72d4bdd9-2ade-4d53-a24e-3372b81a9755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>With Learning JavaScript Design Patterns, you'll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-da</value>
      <webElementGuid>113f7a74-9ef6-41d9-9214-0589ef04ff9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description-wrapper&quot;)/div[@class=&quot;col-md-9 col-sm-12&quot;]/label[@id=&quot;userName-value&quot;]</value>
      <webElementGuid>38a9499e-bc65-4797-b9e5-c0ecd577d8be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//label[@id='userName-value'])[8]</value>
      <webElementGuid>eafb6e95-b373-4c48-98df-3ca792c5576d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='description-wrapper']/div[2]/label</value>
      <webElementGuid>2b584bf9-ddc6-48d1-9a47-4d839f65e936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/label</value>
      <webElementGuid>81bfd331-9f32-4e9e-aad2-c3b53c715b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'userName-value' and (text() = concat(&quot;With Learning JavaScript Design Patterns, you&quot; , &quot;'&quot; , &quot;ll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-da&quot;) or . = concat(&quot;With Learning JavaScript Design Patterns, you&quot; , &quot;'&quot; , &quot;ll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-da&quot;))]</value>
      <webElementGuid>639a08a0-6a60-44ab-98dc-31000b629b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
