<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This pocket guide is the perfect on-t_2b40fb</name>
   <tag></tag>
   <elementGuidId>af9a5ba8-6c71-4460-9328-9d0d04f7f6d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description-wrapper > div.col-md-9.col-sm-12 > #userName-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[@id='userName-value'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2d5e4790-3c62-4d8e-929c-02baec802f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>e589ba39-91a2-4780-8ed8-2c304d2962c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>77124591-6d53-4bdc-afda-083fef702eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName-value</value>
      <webElementGuid>a33881db-bce1-41ab-a06f-309258d7fb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git exp</value>
      <webElementGuid>6bc29874-6129-48be-b24e-c2fd52b5aeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description-wrapper&quot;)/div[@class=&quot;col-md-9 col-sm-12&quot;]/label[@id=&quot;userName-value&quot;]</value>
      <webElementGuid>3384a6bb-b2c3-4421-a9ab-534598dab8ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//label[@id='userName-value'])[8]</value>
      <webElementGuid>c8734eb7-bb97-40ed-b646-8b221be07792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='description-wrapper']/div[2]/label</value>
      <webElementGuid>6c39935f-dfb7-4d40-88ae-31c42ea9bee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/label</value>
      <webElementGuid>d1b052d3-f47c-40ee-a2d2-80712af75093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'userName-value' and (text() = 'This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git exp' or . = 'This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git exp')]</value>
      <webElementGuid>4192e96c-c81f-4ab6-a1ee-48d356ba8256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
